cd Bank
mkdir client 
mkdir Employees
mkdir   Staff
mkdir Branches
mkdir Platform
mkdir Web 
cd client
touch client {0001..4000}.txt
cd D:/GBBP/Bank/Employees
mkdir upper-class
mkdir middle-class
mkdir lower-class
cd D:/GBBP/Bank/Employees/lower-class
touch lc{0001..4000}.txt
cd D:/GBBP/Bank/Employees/middle-class
touch mc{0001..4000}.txt
cd D:/GBBP/Bank/Employees/upper-class
touch uc{0001..4000}.txt
cd D:/GBBP/Bank/Staff
touch staff{001..100}.txt
cd D:/GBBP/Bank/Branches
touch branch{001..080}.txt
cd D:/GBBP/Bank/Platform
mkdir mobile
cd D:/GBBP/Bank/Platform/mobile
cd D:/GBBP/Bank/Web
mkdir IOS ANDROID
mkdir Features
cd D:/GBBP/Bank/Web/Features
touch feature{001..040}.txt
cd D:/GBBP/Bank/Employees/lower-class
touch lc{0001..4000}.txt
cd D:/GBBP/Bank/Employees/middle-class
touch mc{0001..4000}.txt
cd D:/GBBP/Bank/Employees/upper-class
touch uc{0001..4000}.txt
cd D:/GBBP
mkdir Bank-2
cd D:/GBBP
mkdir Bank-3
